php:
    build: ./docker/.
    container_name: php-7.4
    ports:
    - "80:80"
    - "443:443"
    volumes: 
    - ./:/var/www/html/innout
    - ./conf:/etc/apache2/sites-available
    links:
    - db
db:
    image: mysql:latest
    container_name: mysql-php
    ports:
    - "3306:3306"
    volumes: 
    - /var/lib/mysql
    environment: 
    - MYSQL_ROOT_PASSWORD=root